# Generated by Django 6.0.5 on 2026-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('dimenciones', models.CharField(choices=[('CH', 'CHICO'), ('M', 'MEDIANO'), ('G', 'GRANDE')], default='CH', max_length=2)),
            ],
        ),
    ]
