# Generated by Django 6.0.5 on 2026-06-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PU', 'Publicado'), ('DR', 'Borrador'), ('PR', 'Privado')], default='DR', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('published_timestamp', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
                'abstract': False,
            },
        ),
    ]
