# Generated by Django 6.0.5 on 2026-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('AZ', 'AZUL'), ('RO', 'ROJO'), ('VE', 'VERDE'), ('AM', 'AMARILLO'), ('NE', 'NEGRO'), ('BL', 'BLANCO'), ('GR', 'GRIS'), ('NA', 'NARANJA'), ('ROSA', 'ROSA'), ('MO', 'MORADO')], default='NA', max_length=4),
        ),
    ]
